name: Multi-Repo Build Slingshot

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      spd_metamodel_branch:
        description: 'SPD-Metamodel branch'
        required: false
        default: 'fix-for-standalone-building'
      slingshot_branch:
        description: 'Slingshot branch'
        required: false
        default: 'master'
      slingshot_extension_monitoring_branch:
        description: 'Slingshot-Extension-Monitoring branch'
        required: false
        default: 'add_pom_for_e2e_tests'
      slingshot_extension_pcm_core_branch:
        description: 'Slingshot-Extension-PCM-Core branch'
        required: false
        default: 'add_pom_for_e2e_testing'
      slingshot_extension_spd_interpreter_branch:
        description: 'Slingshot-Extension-SPD-Interpreter branch'
        required: false
        default: 'add_pom_for_e2e_tests'
  repository_dispatch:
    types: [build-trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout E2E (self)
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-E2E-Tests'
        path: 'Palladio-Analyzer-Slingshot-E2E-Tests'
        ref: 'changes_for_pipeline'

    - name: Checkout SPD-Metamodel
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Addons-SPD-Metamodel'
        path: 'Palladio-Addons-SPD-Metamodel'
        ref: ${{ github.event.inputs.spd_metamodel_branch }}

    - name: Checkout Slingshot
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot'
        path: 'Palladio-Analyzer-Slingshot'
        ref: ${{ github.event.inputs.slingshot_branch }}

    - name: Checkout Slingshot-Extension-Monitoring
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-Monitoring'
        path: 'Palladio-Analyzer-Slingshot-Extension-Monitoring-master'
        ref: ${{ github.event.inputs.slingshot_extension_monitoring_branch }}

    - name: Checkout Slingshot-Extension-PCM-Core
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core'
        path: 'Palladio-Analyzer-Slingshot-Extension-PCM-Core-master'
        ref: ${{ github.event.inputs.slingshot_extension_pcm_core_branch }}

    - name: Checkout SPD-Interpreter-master
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-SPD-Interpreter'
        path: 'Palladio-Analyzer-Slingshot-Extension-SPD-Interpreter-master'
        ref: ${{ github.event.inputs.slingshot_extension_spd_interpreter_branch }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build SPD-Metamodel
      run: mvn -B clean install
      working-directory: ./Palladio-Addons-SPD-Metamodel
    
    - name: Build Slingshot
      run: mvn -B clean install
      working-directory: ./Palladio-Analyzer-Slingshot

    - name: Build E2E
      run: mvn -B clean install
      working-directory: ./Palladio-Analyzer-Slingshot-E2E-Tests
