name: Multi-Repo Build Slingshot

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [build-trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout E2E (self)
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-E2E-Tests'
        path: 'Palladio-Analyzer-Slingshot-E2E-Tests'
        ref: 'changes_for_pipeline'

    - name: Checkout SPD-Metamodel
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Addons-SPD-Metamodel'
        path: 'Palladio-Addons-SPD-Metamodel'
        ref: 'fix-for-standalone-building'

    - name: Checkout Slingshot
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot'
        path: 'Palladio-Analyzer-Slingshot'
        ref: 'master'

    - name: Checkout Slingshot-Extension-Monitoring
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-Monitoring'
        path: 'Palladio-Analyzer-Slingshot-Extension-Monitoring'
        ref: 'add_pom_for_e2e_tests'

    - name: Checkout Slingshot-Extension-PCM-Core
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core'
        path: 'Palladio-Analyzer-Slingshot-Extension-PCM-Core'
        ref: ${{ github.event.client_payload.slingshot_extension_pcm_core_branch || 'add_pom_for_e2e_testing' }}

    - name: Checkout SPD-Interpreter-master
      uses: actions/checkout@v3
      with:
        repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-SPD-Interpreter'
        path: 'Palladio-Analyzer-Slingshot-Extension-SPD-Interpreter'
        ref: 'add_pom_for_e2e_tests'

    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build SPD-Metamodel
      run: mvn -B clean install
      working-directory: ./Palladio-Addons-SPD-Metamodel
    
    - name: Build Slingshot
      run: mvn -B clean install
      working-directory: ./Palladio-Analyzer-Slingshot

    - name: Build E2E
      run: mvn -B clean install
      working-directory: ./Palladio-Analyzer-Slingshot-E2E-Tests
